
import { Question } from './types';

export const QUESTIONS: Question[] = [
  { id: 1, text: "당면한 문제를 해결하는데 도움이 되는 구체적 방안을 제안한다." },
  { id: 2, text: "어떤 말을 하고자 하는지 사전에 전체 개요를 알려준다." },
  { id: 3, text: "제안하는 것이 성공할 수 있다는 가능성 높은 근거를 제시한다." },
  { id: 4, text: "이야기를 마치면서 다시 한번 전체 내용을 짧게 요약해 준다." },
  { id: 5, text: "확신에 가득 찬 모습으로 기대, 또는 요청 사항을 직접적으로 전달한다." },
  { id: 6, text: "요구사항을 들어주지 않을 때에는 실망감을 솔직히 표현한다." },
  { id: 7, text: "요구사항을 수락할 경우 받게 될 보상이 무엇인지 알려준다." },
  { id: 8, text: "요구사항을 충분히 잘 수행할 것이라는 상대방에 대한 신뢰를 표현한다." },
  { id: 9, text: "주장을 펼치거나 설득하지 않고, 질문으로 상황을 유도한다." },
  { id: 10, text: "상대방의 말을 다시 진술하거나 요약하여 잘 듣고 있음을 표현한다." },
  { id: 11, text: "잘 해내기 위해서 무엇이 필요한지 질문한다." },
  { id: 12, text: "상대가 끝까지 자기입장을 고수하면 잠시 쉬자고 제안한다." },
  { id: 13, text: "상대방과 유사한 것 (취미, 경험, 경력 등)을 찾아 공유한다." },
  { id: 14, text: "상대방과의 과거 경험, 일화 등을 사실적으로 묘사하여 들려준다." },
  { id: 15, text: "자신의 감정이나 생각을 솔직하게 표현하여 신뢰를 구축한다." },
  { id: 16, text: "자신의 꿈과 비전을 상대방과 공유한다." },
  { id: 17, text: "상대방이 해야 할 것이 무엇인지 분명하게 제안한다." },
  { id: 18, text: "이야기의 시작, 본론, 결말을 나누어서 분명히 알려준다." },
  { id: 19, text: "제안한 일을 통해 얻게 될 이익을 설명해 준다." },
  { id: 20, text: "자신이 한 말의 핵심을 중요 단어 제시로 마무리 한다." },
  { id: 21, text: "자신이 원하는 바를 강력하게 구체적으로 지시한다." },
  { id: 22, text: "요청 사항을 상대방이 받아들이면 감사함을 표현한다." },
  { id: 23, text: "요구 사항을 수락하지 않을 경우 불이익이 따를 것을 경고한다." },
  { id: 24, text: "상대방에게 다른 사람들보다 더 뛰어나게 잘 할 수 있음을 상기시킨다." },
  { id: 25, text: "상대방을 가르치려 하지 않고, 질문을 통해 스스로 답을 찾도록 이끈다." },
  { id: 26, text: "상대방의 발언 내용 뿐만 아니라 속에 숨어 있는 감정에도 귀를 기울인다." },
  { id: 27, text: "문제 해결을 위해 좋은 방법이 있으면 알려달라고 요청한다." },
  { id: 28, text: "상대가 문제해결 의지를 강하게 표현하면 고마움과 지지를 표현한다." },
  { id: 29, text: "자유롭게 의견 개진을 할 수 있도록 부드러운 분위기를 조성한다." },
  { id: 30, text: "그림 그리듯 상세한 표현으로 상대방의 몰입을 끌어낸다." },
  { id: 31, text: "자신의 과거 경험담, 실패 사례를 솔직히 이야기 한다." },
  { id: 32, text: "미래에 대한 희망과 열망을 표현한다." },
  { id: 33, text: "문제 해결을 위한 구체적이고 실행 가능한 것을 제안한다." },
  { id: 34, text: "이야기가 길어질 때에는 첫째, 둘째 등으로 나누어 구분하여 말한다." },
  { id: 35, text: "상대방의 입장과 이익에 부합하는 근거를 논리적으로 제시한다." },
  { id: 36, text: "마무리 시점에 상대방에게 요청한 바를 다시 한번 짧게 기억시킨다." },
  { id: 37, text: "이야기를 하면서 에너지로 상대방을 압도한다." },
  { id: 38, text: "자신의 요구가 관절되지 않은 것에 대한 섭섭함을 분명히 표현한다." },
  { id: 39, text: "요구를 들어주는 대가로 직무 관련 혜택을 제공하겠다고 알려준다." },
  { id: 40, text: "상대에 대한 리더의 믿음을 표현하며 격려한다." },
  { id: 41, text: "가벼운 질문으로 대화 분위기를 부드럽게 이끈다." },
  { id: 42, text: "자신의 의견과 상반되는 의견에도 반대하거나 비판하지 않는다." },
  { id: 43, text: "상대방이 생각하는 해결책은 무엇인지 물어본다." },
  { id: 44, text: "문제 해결책이 도출되지 않으면 좀 더 상세한 실행방안을 제시한다." },
  { id: 45, text: "좋은 감정을 가질 수 있도록 상대방에게 우호적으로 행동한다." },
  { id: 46, text: "자신이 꿈꾸는 미래 비전에 대해 상세하게 설명한다." },
  { id: 47, text: "근거 제시나 논리적 대화보다는 감성적인 분위기로 대화를 즐긴다." },
  { id: 48, text: "자신의 열정과 비전을 솔직하게 표현한다." },
];

export const CATEGORIES = [
  {
    name: "논리적 설득 (Logical Persuasion)",
    color: "#3b82f6",
    subFactors: [
      { id: 1, label: "제안 (Proposal)", questionIds: [1, 17, 33] },
      { id: 2, label: "구조화 (Structuring)", questionIds: [2, 18, 34] },
      { id: 3, label: "논리 (Logic)", questionIds: [3, 19, 35] },
      { id: 4, label: "결론 (Conclusion)", questionIds: [4, 20, 36] },
    ],
  },
  {
    name: "카리스마 (Charisma)",
    color: "#ef4444",
    subFactors: [
      { id: 5, label: "카리스마 (Presence)", questionIds: [5, 21, 37] },
      { id: 6, label: "감정 형상화 (Emotional Shaping)", questionIds: [6, 22, 38] },
      { id: 7, label: "보상 압력 (Reward/Pressure)", questionIds: [7, 23, 39] },
      { id: 8, label: "긍정 유도 (Positive Induction)", questionIds: [8, 24, 40] },
    ],
  },
  {
    name: "자각 유도 (Self-Awareness)",
    color: "#10b981",
    subFactors: [
      { id: 9, label: "질문 (Questioning)", questionIds: [9, 25, 41] },
      { id: 10, label: "경청 (Listening)", questionIds: [10, 26, 42] },
      { id: 11, label: "진술 유도 (Statement Induction)", questionIds: [11, 27, 43] },
      { id: 12, label: "지지 강화 (Support/Empower)", questionIds: [12, 28, 44] },
    ],
  },
  {
    name: "감성 합일 (Emotional Unity)",
    color: "#8b5cf6",
    subFactors: [
      { id: 13, label: "라포 형성 (Rapport)", questionIds: [13, 29, 45] },
      { id: 14, label: "이미지 제시 (Image Casting)", questionIds: [14, 30, 46] },
      { id: 15, label: "자기 노출 (Self-Disclosure)", questionIds: [15, 31, 47] },
      { id: 16, label: "비전 결의 (Vision Commitment)", questionIds: [16, 32, 48] },
    ],
  },
];
